### PR TITLE
Fix typo on landing page

### PR DESCRIPTION
**Pull request by zachallett**

### CODE REVIEW

**Comment by StephenOTT** [comment]
Good catch!  :+1:

**Comment by StephenOTT** [comment]
Change is merged and live on github-reminders.com demo site.

**Comment by StephenOTT** [comment]
@zhallett Were you able to receive a reminder?

**Comment by zachallett** [comment]
@StephenOTT I haven't given that a look yet, just started a preliminary look at the overall repository and saw the typo

**Pull request merged**
